### PR TITLE
Adds the NodeJS backend and make rendering the webpages successfully

### PR DESCRIPTION
**Pull request by ankur0904**
I successfully added the NodeJS backend and make the web application working with the backend.

### CODE REVIEW

**Comment by ankur0904** [comment]
Please review it and merge it.

**Comment by ShravaniAK** [comment]
please resolve conflicts

**Comment by ankur0904** [comment]
I am unable to resolve. Can you please help me???

**Comment by ankur0904** [comment]
I changes the folder name so that I integrate the NodeJS backend.

**Comment by ankur0904** [comment]
Please review it.

**Pull request closed without merging**
