### PR TITLE
fixed contact form and search in nav

### PR DESCRIPTION
**Pull request by dyarawilliams**
Completed Issue #72

### CODE REVIEW

**Comment by dyarawilliams** [comment]
This is how It looks

noterjs

**Comment by dyarawilliams** [comment]
@ShravaniAK I fixed the merge conflict and the margin on the nav of the contact.html search form

**Comment by ShravaniAK** [comment]
merge conflicts are still there

**Comment by dyarawilliams** [comment]
@ShravaniAK resolved conflicts

**Pull request merged**
