### PR TITLE
New UI - Purple

### PR DESCRIPTION
**Pull request by CDPhu**
#2 
In this, I added

   The style for font, body, navbar, buttons and search bar
   Animated Background fitting the theme
   Currently unused (for now) style for dropdown menu
Reference:
noterjs
Note: the background will change colour overtime, being a gradient

### CODE REVIEW

**Comment by ShravaniAK** [comment]
please resolve the merge conflicts

**Review by ShravaniAK — APPROVED** [review]

**Comment by CDPhu** [comment]
It's been a pleasure working with you

**Comment by CDPhu** [comment]
Could you also add the "hacktoberfest-accepted" label in merge? It would mean a lot.

**Comment by ShravaniAK** [comment]
thanks for working , great work

**Pull request merged**
